### ISSUE TITLE
Blueprint book import crash to landing page

### ISSUE THREAD

**Issue by rpdelaney** [dstockhammer/factorio-tech#21]
Blueprint string: https://pastebin.com/ZtWjtHzh

When importing this, I was dropped back to the landing page and the blueprint does not appear.

**Comment by rpdelaney** [comment]
Very annoying how blueprint strings look like base64 encoded viruses to pastebin's heuristics...

**Comment by veksen** [comment]
Do you have another version of that blueprint string?

**Comment by rpdelaney** [comment]
I honestly don't remember what it was. I'll reopen this if I can duplicate the problem (and I'll put it in a gist next time).
